name: Generate Disgusting Domains List

on:
  schedule:
    - cron: "0 0 * * 4"
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set variables
        run: |
          echo "RELEASE_NAME=$(date +%Y%m%d)" >> $GITHUB_ENV
        shell: bash
        
      - name: Download files
        run: |
          wget https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/facebook -O facebook.list
          wget https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/iqiyi -O iqyi.list
          wget https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/douyu -O douyu.list
          wget https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/facebook-dev -O facebook-dev.list
          wget https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/gigabyte -O gigabyte.list
          wget https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/hm -O hm.list
          wget https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/huya -O huya.list
          wget https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/instagram -O instagram.list
          wget https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/jd -O jd.list
          wget https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/nike -O nike.list
          wget https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/sina -O sina.list
          wget https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/tiktok -O tiktok.list
          wget https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/twitter -O twitter.list
          wget https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/uc -O uc.list
          wget https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/umeng -O umeng.list
          wget https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/youku -O youku.list
          wget https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/xiaomi -O xiaomi.list
          wget https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/adidas -O aidas.list
          wget https://raw.githubusercontent.com/so1ar/disgusting-domains/main/2345 -O 2345.list
          wget https://raw.githubusercontent.com/so1ar/disgusting-domains/main/pdd -O pdd.list
          wget https://raw.githubusercontent.com/so1ar/disgusting-domains/main/360 -O 360.list
          wget https://raw.githubusercontent.com/so1ar/disgusting-domains/main/bytedance -O bytedance.list
          wget https://raw.githubusercontent.com/so1ar/disgusting-domains/main/kuaishou -O kuaishou.list

      - name: generate list
        run: |
          cat *.list > output
          sed -i '/include:/d' output
          sed -i '/sinaimg/d' output
          sed -i '/#/d' output
          sed -i 's/full://g' output
          sed -i 's/@cn//g' output
          sed -i '/^\s*$/d' output
          awk '{print "||" $0}' output | awk '{print $0 "^"}' > rules
          mkdir publish
          mv output ./publish/domains
          mv rules ./publish
          
      - name: Git push assets to "release" branch
        run: |
          cd publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add geoip "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u geoip release
